import type {State} from '../../shared/types';
const links=[['Picsart Support Center','https://support.picsart.com'],['Email plugin support','mailto:plugins@picsart.com?subject=Picsart%20Commerce%20Support'],['Terms of Use','https://picsart.com/terms-of-use/'],['Privacy Policy','https://picsart.com/privacy-policy/'],['Generative AI Additional Terms of Use','https://picsart.com/genaitermsofuse'],['Account help','https://support.picsart.com/hc/en-us/categories/4416517803409-Your-profile-account'],['Subscription and payment help','https://support.picsart.com/hc/en-us/categories/360000192038-Subscription-Payments'],['Credit help','https://support.picsart.com/hc/en-us/sections/19530880111261-Credits'],['AI tools help','https://support.picsart.com/hc/en-us/categories/9341772365341-Picsart-AI-Tools'],['Contact support','https://support.picsart.com/hc/en-us/requests/new']];
export function AccountSettings({state,busy,disconnecting,onDisconnect}:{state:State;busy:boolean;disconnecting:boolean;onDisconnect:()=>void}){
 const connected=state.auth.authenticated;
 return <div className="picsart-settings-grid">
  <section className="live-card"><h2>Picsart account</h2><dl><dt>Connection</dt><dd>{connected?(state.auth.requiresReconnect?'Reconnect required':state.auth.canGenerate?'Connected':'Connected · access needs attention'):'Not connected'}</dd>{connected&&<><dt>Profile</dt><dd>{state.auth.name||'Picsart account'}</dd><dt>Account ID</dt><dd>{state.auth.subject||'Unavailable'}</dd></>}</dl>{connected&&<><a href="https://picsart.com/settings" target="_blank" rel="noopener noreferrer">Manage Picsart profile</a><p>Disconnecting removes this WordPress connection. It does not cancel your subscription or delete your Picsart media.</p><button type="button" className="picsart-disconnect-button" disabled={busy} aria-busy={disconnecting} onClick={onDisconnect}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M9 5H5v14h4M13 8l4 4-4 4M9 12h11"/></svg>{disconnecting?'Disconnecting…':'Disconnect Picsart'}</button></>}</section>
  <section className="live-card"><h2>Plan and credits</h2><dl><dt>Subscription</dt><dd>{connected?<>Manage your subscription on Picsart.com. <a href="https://picsart.com/settings" target="_blank" rel="noopener noreferrer">View plan and billing details</a>.</>:'Connect Picsart to view account information.'}</dd><dt>Credit balance</dt><dd>{connected&&state.credits?`${state.credits.balance.toLocaleString()} credits`:connected?'Balance unavailable':'Connect to view balance'}</dd>{connected&&state.credits&&state.reserved>0&&<><dt>Reserved for active generations</dt><dd>{state.reserved.toLocaleString()} credits</dd></>}</dl><p>Subscriptions and payments are managed on Picsart.com.</p><a href="https://picsart.com/pricing/" target="_blank" rel="noopener noreferrer">Manage plan and top up credits</a></section>
  <section className="live-card"><h2>Legal and support</h2><ul>{links.map(([label,url])=><li key={url}><a href={url} target="_blank" rel="noopener noreferrer">{label}</a></li>)}</ul></section>
 </div>;
}
