import {useEffect,useState,type ReactNode} from 'react';
import {platformFetch,platformEndpoint} from './platform';
export default function ConsentGate({children}:{children:ReactNode}){
 // The page embeds the saved choice; the request is only a fallback for older page markup.
 const [consent,setConsent]=useState<boolean|undefined>(window.picsartStudio.consent);const [checked,setChecked]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function load(){setError('');try{const r=await platformFetch(`${window.picsartStudio.wpEndpoint}/preferences`);const data=await r.json();if(!r.ok)throw new Error(data.message||'Could not load your privacy preference.');setConsent(data.consent===true);}catch(e){setError(e instanceof Error?e.message:'Could not load privacy preference.');}}
 useEffect(()=>{if(consent===undefined)void load();},[]);
 if(consent)return <>{children}</>;
 return <main className="live-main picsart-connect"><h1>Connect Picsart to WordPress</h1><p>Bring Picsart’s creative tools into WordPress. Sign in or create a Picsart account to use cloud tools with your Picsart plan and credits. Manage your subscription and payments on <a href="https://picsart.com/" target="_blank" rel="noopener noreferrer">picsart.com</a>.</p>{consent===false&&<section className="live-card"><h2>Before connecting</h2><p>Connecting lets you use Picsart from WordPress. With your permission, the plugin accesses your Picsart account, credit balance and Drive, and sends the media and prompts needed for the edits or generations you choose. Requesting an AI price quote uploads a copy of your selected photo to Picsart Drive. Your results stay in your Picsart account until you choose to copy them into WordPress.</p><p><a href="https://picsart.com/privacy-policy/" target="_blank" rel="noopener noreferrer">Picsart privacy policy</a> · <a href="https://picsart.com/terms-of-use/" target="_blank" rel="noopener noreferrer">Picsart terms</a> · <a href="https://picsart.com/genaitermsofuse" target="_blank" rel="noopener noreferrer">Generative AI Additional Terms of Use</a></p><p>Next, approve this connection on the Picsart page that opens, after checking that its code matches the one shown here. This page updates automatically. Saving this permission alone does not connect your account.</p><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> Allow the plugin to connect to Picsart and transfer the account information, media and prompts needed for the actions I choose.</label><p><button disabled={!checked||busy} onClick={async()=>{const popup=window.open('about:blank','picsart-connect');if(!popup){setError('Allow the Picsart sign-in tab to open, then try again.');return;}popup.opener=null;popup.document.title='Connecting to Picsart…';popup.document.body.textContent='Preparing Picsart sign-in…';setBusy(true);setError('');try{const r=await platformFetch(`${window.picsartStudio.wpEndpoint}/preferences`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({consent:true})});const data=await r.json();if(!r.ok||data.consent!==true)throw new Error(data.message||'Could not save your preference.');const post=async(path:string,body:unknown)=>{const response=await platformFetch(platformEndpoint(path),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error||'Could not start Picsart sign-in.');return result;};// The studio shows the matching code once consent is saved; this tab only opens the approval page.
const started=await post('/auth/device/start',{});if(started.status==='connected'||started.finishing){popup.close();setConsent(true);return;}if(started.status!=='pending')throw new Error('Picsart sign-in is unavailable. Please try again.');if(!popup.closed)popup.location.replace(started.verificationUriComplete??started.verificationUri);setConsent(true);}catch(e){popup.close();setError(e instanceof Error?e.message:'Could not start Picsart sign-in.');}finally{setBusy(false);}}}>{busy?'Preparing sign-in…':'Connect Picsart'}</button></p></section>}{consent===undefined&&!error&&<p role="status">Loading your privacy preference…</p>}{error&&<div role="alert"><p>{error}</p><button onClick={()=>void load()}>Try again</button></div>}</main>;
}
