import {useRef,useState} from 'react';
import {bannerHtml,calendarReminder,httpsLink} from '../../shared/marketing-export';
export function MarketingExports({image,title='Product story',video=false,attachmentId}:{image?:string;title?:string;video?:boolean;attachmentId?:string|number}){
 const [heading,setHeading]=useState(title),[destination,setDestination]=useState(''),[poster,setPoster]=useState(''),[at,setAt]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');const uid=useRef<string>(crypto.randomUUID());const intent=useRef<{hash:string;id:string}>();const [drafts,setDrafts]=useState<Array<{id:number;title:string;draft:{heading:string;destination:string;poster:string;at:string;uid:string}}>>([]);
 async function request(method:string,body?:unknown){const config=window.picsartStudio;const endpoint=config.wpEndpoint??new URL(config.endpoint,location.href).href.replace(/\/studio(?:\?.*)?$/,'');const url=new URL(endpoint+'/marketing-drafts',location.href);if(url.origin!==location.origin)throw Error('Drafts must stay on this WordPress site.');const response=await fetch(url,{method,credentials:'same-origin',headers:{'X-WP-Nonce':config.nonce,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.message||'Draft unavailable.');return data;}
 async function save(kind:'email'|'reminder'){setError('');try{const body={kind,attachmentId,heading,destination,poster,at:kind==='reminder'?new Date(at).toISOString():''};const hash=JSON.stringify(body);if(intent.current?.hash!==hash)intent.current={hash,id:crypto.randomUUID()};const result=await request('POST',{...body,requestId:intent.current.id});setNotice(`Saved local ${kind} draft #${result.id}. Nothing sent, scheduled or published.`);}catch(e){setError(e instanceof Error?e.message:'Could not save the draft.');}}
 async function load(){try{setDrafts((await request('GET')).filter((d:{draft:{attachmentId:number}})=>String(d.draft.attachmentId)===String(attachmentId)));}catch(e){setError(e instanceof Error?e.message:'Could not load drafts.');}}
 function download(kind:'banner'|'calendar'){setError('');setNotice('');try{httpsLink(destination);const text=kind==='banner'?bannerHtml({heading,destination,image:video?poster:image??'',alt:heading,video}):calendarReminder({id:uid.current,title:heading,at:new Date(at).toISOString(),link:destination});const url=URL.createObjectURL(new Blob([text],{type:kind==='banner'?'text/html;charset=utf-8':'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=kind==='banner'?'picsart-email-banner.html':'picsart-marketing-reminder.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(kind==='banner'?'Downloaded an email banner draft. Import it into your email provider; nothing was sent.':'Downloaded a reminder. Open the file in your calendar to add it; nothing was scheduled or published.');}catch(e){setError(e instanceof Error?e.message:'Could not create this export.');}}
 return <details><summary>Email banner and marketing reminder</summary><p>Create files for your email or calendar app. No email is sent and no social post is scheduled.</p><label>Heading<input maxLength={120} value={heading} onChange={e=>setHeading(e.target.value)}/></label><label>Destination HTTPS link<input type="url" value={destination} onChange={e=>setDestination(e.target.value)}/></label>{video&&<label>Public HTTPS poster image URL<input type="url" value={poster} onChange={e=>setPoster(e.target.value)}/></label>}<p>Email images must be publicly accessible over HTTPS. Local test-site URLs cannot be used by recipients.</p><button onClick={()=>download('banner')}>Download linked email banner</button><label>Reminder time ({Intl.DateTimeFormat().resolvedOptions().timeZone})<input type="datetime-local" value={at} onChange={e=>{setAt(e.target.value);uid.current=crypto.randomUUID();}}/></label><button onClick={()=>download('calendar')}>Download calendar reminder</button>{attachmentId&&<><button onClick={()=>void save('email')}>Save local email draft</button><button onClick={()=>void save('reminder')}>Save local reminder draft</button><button onClick={()=>void load()}>Reopen saved drafts for this media</button>{drafts.map(d=><button key={d.id} onClick={()=>{setHeading(d.draft.heading);setDestination(d.draft.destination);setPoster(d.draft.poster);const date=new Date(d.draft.at);setAt(Number.isFinite(date.getTime())?new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16):'');uid.current=d.draft.uid;setNotice('Draft loaded. Download to use it in your email or calendar app.');}}>{d.title} · #{d.id}</button>)}</>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</details>;
}
