import {platformFetch} from './platform';
import {useEffect,useState} from 'react';
import {notificationCategories,type NotificationCategory} from '../../shared/notification-preferences';
import type {State} from '../../shared/types';
export function StudioHelp(){return <details className="review-notice"><summary>Help and support</summary><p>Connect your Picsart account, select a product photo, and review the exact credit price before generation. Review the finished media before copying it to WordPress.</p><p>Image tools include local edits that do not use generation credits. Background removal and upscale are planned for a later release. The embedded Picsart editor is not available until automatic account provisioning is connected.</p><p>Copying adds a file to the Media Library. Adding a video to a product updates its description after your approval. You can also place media with the Picsart block.</p><p>If an operation needs checking, keep its job ID and check Picsart Drive before retrying. An uncertain submission is not automatically resubmitted.</p><a href="https://support.picsart.com" target="_blank" rel="noopener noreferrer">Open Picsart Support Center</a> · <a href="https://support.picsart.com/hc/en-us/requests/new" target="_blank" rel="noopener noreferrer">Contact Picsart support</a></details>;}
export function NotificationPreferences({state,request,onSaved}:{state:State;request:<T>(path:string,body?:unknown)=>Promise<T>;onSaved:()=>Promise<unknown>}){
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [delivery,setDelivery]=useState<{enabledAt:number;destination:string}>();
 const [deliveryError,setDeliveryError]=useState('');const [deliveryAttempt,setDeliveryAttempt]=useState(0);
 useEffect(()=>{let active=true;setDelivery(undefined);setDeliveryError('');if(state.auth.subject)void request<{enabledAt:number;destination:string}>('/notification-delivery').then(value=>{if(active)setDelivery(value);}).catch(()=>{if(active)setDeliveryError('Could not load email preferences. Your saved choice has not changed.');});return()=>{active=false;};},[state.auth.subject,deliveryAttempt]);
 const preferences=state.notificationPreferences;
 const available=new Set(['setup','started','delayed','ready','exports','attention']);
 if(!preferences||!state.auth.authenticated)return null;
 return <details className="review-notice"><summary>Notification preferences</summary><p>Choose which workspace notices you want. Job status and errors always remain in history. Optional emails use this site’s WordPress mail service. Push, promotions and support-reply subscriptions are not enabled.</p>{deliveryError&&<p role="alert">{deliveryError} <button onClick={()=>setDeliveryAttempt(value=>value+1)}>Retry email preferences</button></p>}{!delivery&&!deliveryError&&<p role="status">Loading email preferences…</p>}{delivery&&<label style={{display:'block'}}><input type="checkbox" disabled={busy} checked={!!delivery.enabledAt} onChange={async e=>{setBusy(true);setError('');try{setDelivery(await request('/notification-delivery',{enabled:e.target.checked}));}catch(e){setError(e instanceof Error?e.message:'Could not save email preference.');}finally{setBusy(false);}}}/> Email me about new jobs at {delivery.destination}</label>}{Object.entries(preferences).filter(([category])=>available.has(category)).map(([category,enabled])=><label key={category} style={{display:'block'}}><input type="checkbox" checked={!!enabled} disabled={busy} onChange={async e=>{setBusy(true);setError('');try{await request('/notification-preferences',{category,enabled:e.target.checked});await onSaved();}catch(error){setError(error instanceof Error?error.message:'Could not save preferences.');}finally{setBusy(false);}}}/> {notificationCategories[category as NotificationCategory]}</label>)}{error&&<p role="alert">{error}</p>}</details>;
}
export function CloudPrivacy(){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details className="review-notice"><summary>Cloud privacy</summary><p>You can disable cloud access for your WordPress account. Picsart tools will be hidden until you allow access again. To disconnect your Picsart account, open Picsart Settings.</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await platformFetch(`${window.picsartStudio.wpEndpoint}/preferences`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({consent:false})});const data=await r.json();if(!r.ok||data.consent!==false)throw new Error(data.message||'Could not disable cloud access.');window.location.reload();}catch(e){setError(e instanceof Error?e.message:'Could not disable cloud access.');setBusy(false);}}}>{busy?'Disabling…':'Disable cloud access'}</button>{error&&<p role="alert">{error}</p>}</details>;
}
